### ISSUE TITLE
Fix (Instrument/Drumkit)Component design

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#1901]
The current design of the components is quite rough and the way the user can them is quite limited. Frankly, I think the only reason we do not have a couple of open issues related to this topic is because no one is actually using this feature.

If an instrument of one drumkit is loaded (by click-dragging) into another one, all instrument components with different name not present as component names in the drumkit will be added. This by itself is more or less fine. But UX is awful and one can't really use it.

- [x] ~There is no way to change the component associated with a layer/sample. E.g. loading an instrument with component "room" into drumkit with component "room mic" results in the drumkit having both "room" and "room mic" as components and there is no way of merging them other than saving and manually rewriting the XML files.~ (#2021)
- [x] ~In the `InstrumentEditor` the component name and all the corresponding options are displayed _below_ the "Instrument" and "Layers" button. This does not indicate at all that this is a property all instruments do share.~ (#2021)
- [x] ~It is not evident at all what will be lost when deleting a component.~ (Can be undone and redone now.)
- [x] ~"Sample Selection" algorithm chosen in the `InstrumentEditor` is affecting all components.~ (#2021)
- [x] ~The `SoundLibrary` does not indicate the components of a kit. It is not evident what happens when loading an instrument from this kit. E.g. if the default component is not called "Main", one might wonder where all the samples are gone before one realizes that the component has to be changed using the drop down menu.~ (#2021)
- [x] ~Why are the drumkit component strips in the mixer do not feature preview button, selection ID, FX, and panning? I mean, I know why. It is not implemented. But it should as it is equally important there. Indication the the corresponding strip belongs to a component should be done differently.~ (#2021)
- [x] Just when toying a round a bit for the last 5 minutes I got two distinct segfaults using the 1.2.2 release. All resulting from the presence of more than one component when entering the `Sampler`. This especially happens when switching drumkits with different component setups
- [x] Hydrogen crashes when adding a component while playback is rolling.
- [x] Undo/redo is not supported for most/all component actions.
- [x] When setting the name of an component to "add", "delete", or "rename", selecting it in the `InstrumentEditor` triggers the corresponding action instead of switching to the component.

I'm afraid to properly support components in Hydrogen we have to redesign a couple of GUI elements. Especially the `InstrumentEditor`. (See #1213)
